# Cheatsheet Notebook

In [59]:
import cv2
import numpy as np
import colour
from scipy import signal

## Farbsysteme

Informationen und Umrechnung der Verschiedenen Farbsysteme

- Additiv: https://lehrerfortbildung-bw.de/st_digital/medienkompetenz/gestaltung-farbe/physik/additiv/addinter/index.html
- Subtraktiv: https://lehrerfortbildung-bw.de/st_digital/medienkompetenz/gestaltung-farbe/physik/subtrakt/subinter/

In [11]:
# https://colour.readthedocs.io/

# CIE xy -> xyz
def xyz_from_xy(x, y):
    """Return the vector (x, y, 1-x-y)."""
    return np.array((x, y, 1-x-y))

In [12]:
colour.XYZ_to_xy(xyz_from_xy(3.0, 3.0))

array([ 3.,  3.])

In [31]:
colour.XYZ_to_xy(colour.wavelength_to_XYZ(550))

array([ 0.3016038 ,  0.69230776])

In [19]:
colour.RGB_to_HSV((1, 1, 0))

array([ 0.16666667,  1.        ,  1.        ])

In [20]:
colour.RGB_to_CMY((1, 1, 0))

array([ 0.,  0.,  1.])

In [23]:
colour.CMY_to_CMYK(colour.RGB_to_CMY((1, 1, 0)))

array([ 0.,  0.,  1.,  0.])

In [26]:
colour.HSV_to_RGB((240, 0, 0.5))

array([ 0.5,  0.5,  0.5])

In [28]:
colour.RGB_to_CMY(colour.HSV_to_RGB((240, 0, 0.5)))

array([ 0.5,  0.5,  0.5])

## Histogramme

Berechnen und Histogramausgleich

In [41]:
cv2.equalizeHist(np.uint8([
    [0, 1, 1, 2, 2],
    [2, 1, 1, 2, 2],
    [4, 5, 6, 7, 7],
    [8, 8, 7, 7, 7],
    [8, 8, 9, 9, 9]
]))

array([[  0,  42,  42,  96,  96],
       [ 96,  42,  42,  96,  96],
       [106, 117, 128, 181, 181],
       [223, 223, 181, 181, 181],
       [223, 223, 255, 255, 255]], dtype=uint8)

## Faltungen

Faltungen von hand und mit numpy berechnen

Beispiel:

- f: (0, 0, 0, 1, 1, 0, 0, 0)
- w: (1, 2, 2, 2, 1)

![faltung](img/faltung.png)

In [48]:
# faltung von f * w

f = np.array([0, 0, 0, 1, 1, 1, 0, 0, 0])
w = np.array([1, 2, 2, 2, 1])

np.convolve(f, w)

array([0, 0, 0, 1, 3, 5, 6, 5, 3, 1, 0, 0, 0])

In [51]:
# korrelation von g ox h

g = np.array([1, 1, 0, 0, 1, 1, 0, 0])
h = np.array([0, 1, 1, 0])

np.correlate(g, h, "full")

array([0, 1, 2, 1, 0, 1, 2, 1, 0, 0, 0])

In [52]:
# man beachte
np.correlate(g, h, "full") == np.convolve(g, h)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [61]:
# 2d example
f = np.array([
    [1, 2, 3],
    [0, 1, 2],
    [4, 3, 1]
])
w = np.array([
    [1, 2, 1],
    [2, 4, 2],
    [1, 2, 1]
])

signal.convolve2d(f, w)

array([[ 1,  4,  8,  8,  3],
       [ 2,  9, 20, 21,  8],
       [ 5, 17, 27, 23,  8],
       [ 8, 23, 26, 15,  4],
       [ 4, 11, 11,  5,  1]])